config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :languages
    resources :solutions
  end

  get '/signup', to: 'users#new', as: 'signup'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  root 'sessions#new'
  post '/sessions', to: 'sessions#create'
  post 'users', to: 'users#create', as: 'create_user'

  get ':alias/overview', to: 'headquarters#overview', as: 'overview'

  get '/:alias/solutions', to: 'solutions#index', as: 'solutions'
  get '/:alias/solutions/:programming_language', to: 'solutions#index', as: 'solutions_in_language'
  get '/:alias/new_solution/', to: 'solutions#new', as: 'new_solution'
  post '/:alias/solutions', to: 'solutions#create', as: 'create_new_solution'
  get '/:alias/solutions/edit/:id', to: 'solutions#edit', as: 'edit_solution'
  patch '/:alias/solutions/:id', to: 'solutions#update', as: 'update_solution'
  get 'solution/:id', to: 'solutions#show', as: 'solution'
  delete 'solution/:id', to: 'solutions#destroy', as: 'destroy_solution'

  get 'languages/new', to: 'langauges#new', as: 'new_languages'
  # get 'solutions/new/:programming_language', to: 'solutions#new', as: 'new_solution_in_language'
  post 'languages', to: 'languages#create'
end

app/controllers/headquarters_controller.rb
class HeadquartersController < ApplicationController
  before_action :authenticate_user!, only: [:overview]
  before_action :set_user, :set_languages, :set_solutions

  def overview
    @top_four_languages = @solutions.each_with_object(Hash.new(0)) do |solution, hash|
                            hash[solution.programming_language] += 1
                          end.sort_by { |_, value| -value }.first(4).to_h

    months_count = Hash.new(0)
    %w[Jan Feb Mar Apr May Jun
       Jul Aug Sep Oct Nov Dec].each do |month|
      months_count[month] = 0
    end
    @solutions = @solutions.each_with_object(months_count) do |solution, hash|
      hash[solution.created_at.strftime('%B')[0..2]] += 1
    end
  end

  private

  def set_user
    @user = current_user
  end

  def set_languages
    @languages = @user.solutions.map(&:programming_language).uniq
  end

  def set_solutions
    @solutions = @user.solutions
  end
end

app/helpers/headquarters_helper.rb
module HeadquartersHelper
end

app/views/headquarters/overview.html.erb
<div class='flex justify-center mx-4 mt-2'>
  <div
    class='
      w-full md:w-full lg:w-[1216px] flex flex-col md:grid
      md:grid-cols-[auto_0_minmax(0,_calc(100%-265px-24px))] lg:grid
      lg:grid-cols-[auto_0_minmax(0,_calc(100%-296px-24px))] gap-6 pt-8 pb-6
    '
  >
    <!-- sidebar -->
    <aside
      class='
        md:min-w-[256px] lg:min-w-[296px] md:col-start-1 md:col-end-3 lg:col-start-1
        lg:col-end-3 flex items-center md:flex-col lg:flex-col md:items-start
        lg:items-start gap-4 border-[1px] border-solild border-gray-150 border-t-0
        border-l-0 border-r-0 md:border-0 lg:border-0 pb-10 md:pb-0 lg:pb-0
      '
    >
      <div class='max-w-[296px] flex flex-col gap-4'>
        <div class='flex gap-4 md:flex-col lg:flex-col'>
          <div class='block md:hidden lg:hidden'>
            <%= identicon_for user: @user, identicon_width: 60, identicon_height: 60 %>
          </div>
          <div class='hidden md:block lg:hidden'>
            <%= identicon_for user: @user, identicon_width: 256, identicon_height: 256 %>
          </div>
          <div class='hidden md:hidden lg:block'>
            <%= identicon_for user: @user, identicon_width: 296, identicon_height: 296 %>
          </div>
          <div>
            <h1 class='font-bold text-2xl'>
              <%= @user.alias %>
            </h1>
            <div class='text-xl text-gray-200'>
              <span><%= @user.email %></span>
            </div>
          </div>
        </div>
        <div class='text-md'>
          <p><%= @user.bio %></p>
        </div>
        <button
          class='
            w-full bg-gray-300 border-[1px] border-solid border-gray-150 rounded-md py-1
          '
        >
          <span class='text-sm'>Edit profile</span>
        </button>
      </div>
    </aside>
    <!-- dashboard -->
    <div class='md:col-start-3 lg:col-start-3 flex flex-col gap-8'>
      <div class='flex flex-col gap-4'>
        <h2>Top languages</h2>
        <div
          class='
            flex flex-col md:flex-row lg:flex-row md:flex-wrap lg:flex-wrap gap-4
          '
        >
          <% if @top_four_languages.empty? %>
            <div
              class='
                w-full h-[14rem] flex justify-center items-center border-[1px] border-solid
                border-gray-150 rounded-md
              '
            >
              <div class='flex flex-col items-center text-lg gap-2'>
                <i class="fa-solid fa-flask-vial"></i>
                <span>Oops! No solutions yet...</span>
              </div>
            </div>
          <% else %>
            <% @top_four_languages.each do |language, count| %>
              <div
                class='
                  flex-grow w-full p-4 md:w-[49%] lg:w-[49%] border-[1px] border-solid
                  border-gray-150 rounded-md text-sm flex flex-col gap-4
                '
              >
                <div class='flex justify-between'>
                  <div class='flex gap-2 items-center'>
                    <i class="fa-solid fa-keyboard"></i>
                    <a href="<%= solutions_in_language_path(programming_language: language) %>">
                      <span class='font-bold text-blue-500'><%= language %></span>
                    </a>
                    <div class='flex items-center h-full'>
                      <span
                        class='
                          border-[1px] border-solid border-gray-150 rounded-2xl px-2 text-gray-200 text-xs
                        '
                      ><%= count %>
                      </span>
                    </div>
                  </div>
                  <div class='text-gray-200 hidden md:hidden lg:block'>
                    <span>Last use:</span>
                    <span><%= @user.solutions_in(language).last.updated_at.strftime("%B %d") %></span>
                  </div>
                </div>
                <div class='flex flex-col gap-2 h-full'>
                  <div class='flex text-md'>
                    <span class='truncate'><%= @user.solutions_in(language).last.title %></span>
                  </div>
                  <span class='text-sm text-gray-200 truncate'><%= @user.solutions_in(language).last.instructions %></span>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>

      <div class='flex flex-col gap-4 '>
        <h2>Practice frequency</h2>
        <div class='border-[1px] border-solid border-gray-150 rounded-md p-4'>
          <%= area_chart @solutions, colors: %w[#38D352], height: "400px" %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/headquarters/repositories.html.erb
<div>
  <h1 class="font-bold text-4xl">Headquarters#repositories</h1>
  <p>Find me in app/views/headquarters/repositories.html.erb</p>
</div>

app/views/headquarters/solutions.html.erb
<div
  class='
    min-h-svh flex justify-between gap-0 border-[1px] border-solid border-gray-150
    border-t-0 border-l-0 border-r-0
  '
>
  <div
    class='
      hidden md:block lg:block min-w-80 border-[1px] border-solid border-gray-150
      border-t-0 border-l-0 border-b-0
    '
  >
    <div class='h-full flex flex-col'>
      <div
        class='
          border-[1px] border-solid border-gray-150 border-t-0 border-l-0 border-r-0 p-4
          flex justify-between items-center
        '
      >
        <h2 class='text-sm'>Languages</h2>
        <button class='h-8 w-8 border-[1px] border-solid border-gray-400 rounded-md'>
          <i class="fa-solid fa-plus text-gray-400 text-sm"></i>
        </button>
      </div>
      <div class='h-full p-4 text-sm overflow-auto'>
        <div class='justify-center pb-2'>
          <div class='flex items-center gap-2'>
            <i class="fa-solid fa-glasses text-gray-400"></i>
            <%= @user.alias %>
          </div>
        </div>
        <% @languages.each do |language| %>
          <div class='flex items-center gap-2 pl-2 pb-2'>
            <i class="fa-solid fa-keyboard text-gray-400"></i>
            <%= language.name %>
            <span
              class='
                border-[1px] border-solid border-gray-150 rounded-2xl px-2 text-gray-200 text-xs
              '
            >
              <%= language.solutions.count %>
            </span>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div>

  </div>
</div>