config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :languages
    resources :solutions
  end

  get '/signup', to: 'users#new', as: 'signup'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  root 'sessions#new'
  post '/sessions', to: 'sessions#create'
  post 'users', to: 'users#create', as: 'create_user'

  get ':alias/overview', to: 'headquarters#overview', as: 'overview'

  get '/:alias/solutions', to: 'solutions#index', as: 'solutions'
  get '/:alias/solutions/:programming_language', to: 'solutions#index', as: 'solutions_in_language'
  get '/:alias/new_solution/', to: 'solutions#new', as: 'new_solution'
  post '/:alias/solutions', to: 'solutions#create', as: 'create_new_solution'
  get '/:alias/solutions/edit/:id', to: 'solutions#edit', as: 'edit_solution'
  patch '/:alias/solutions/:id', to: 'solutions#update', as: 'update_solution'
  get 'solution/:id', to: 'solutions#show', as: 'solution'
  delete 'solution/:id', to: 'solutions#destroy', as: 'destroy_solution'

  get 'languages/new', to: 'langauges#new', as: 'new_languages'
  # get 'solutions/new/:programming_language', to: 'solutions#new', as: 'new_solution_in_language'
  post 'languages', to: 'languages#create'
end

app/models/solution.rb
class Solution < ApplicationRecord
  belongs_to :user
  belongs_to :language

  before_validation :find_or_set_language_id
  before_update :downcase_tags
  before_save :downcase_tags
  before_save { programming_language.capitalize! }
  before_save { title.capitalize! }

  validates :title, presence: true, length: { maximum: 60 }
  validates :instructions, presence: true
  validates :attempt, presence: true
  validates :programming_language, presence: true
  validates :tags, presence: true
  validates :language_id, presence: true
  validate :language_must_exist

  private

  def find_or_set_language_id
    capitalized_programming_language = programming_language.capitalize
    programming_language_on_record = Language.find_by(name: capitalized_programming_language)

    if programming_language_on_record
      self.language_id = programming_language_on_record.id
    else
      new_language = Language.create(name: capitalized_programming_language)
      self.language_id = new_language.id
    end
  end

  def downcase_tags
    self.tags = tags.map(&:downcase)
  end

  def language_must_exist
    errors.add(:language_id, 'must exist') unless Language.exists?(id: language_id)
  end
end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  before_action :authenticate_user!, only: %i[index show new create edit update destroy]
  before_action :set_user, :set_languages, :set_solutions, :set_solution

  def index; end

  def show; end

  def new
    @solution = @user.solutions.new
  end

  def create
    @solution = @user.solutions.new(solution_params)
    @solution.tags = params[:solution][:tags].split(',').map(&:strip) if params[:solution][:tags].present?

    respond_to do |format|
      if @solution.save
        format.html do
          redirect_to solutions_in_language_path(programming_language: @solution.programming_language),
                      notice: 'Solution was successfully created.'
        end
        format.json { render :show, status: :created, location: @solution }
      else
        puts "ERRORS: #{@solution.errors.full_messages}"
        format.html { redirect_to solutions_path :new, status: :unprocessable_entity }
        format.json { render json: @solution.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @solution = @user.solutions.find(params[:id])
  end

  def update
    @solution = @user.solutions.find(params[:id])
    tags_array = solution_params[:tags].split(',').map(&:strip) if solution_params[:tags].present?

    respond_to do |format|
      if @solution.update(tags: tags_array)
        if @solution.update(solution_params.except(:tags))
          format.html do
            redirect_to solutions_in_language_url(programming_language: @solution.programming_language),
                        notice: 'Solution was successfully updated.'
          end
          format.json { render :show, status: :ok, location: @solution }
        else
          puts "ERRORS: #{@solution.errors.full_messages}"
          format.html { redirect_to solutions_path :new, status: :unprocessable_entity }
          format.json { render json: @solution.errors, status: :unprocessable_entity }
        end
      else
        puts "ERRORS: #{@solution.errors.full_messages}"
        format.html { redirect_to solutions_path :new, status: :unprocessable_entity }
        format.json { render json: @solution.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @solution = @user.solutions.find(params[:id])
    language_of_to_delete = @solution.programming_language
    @solution.destroy!

    respond_to do |format|
      format.html do
        redirect_to solutions_path(@user.alias),
                    notice: 'Solution was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = current_user
  end

  def set_languages
    @languages = @user.solutions.map(&:programming_language).uniq.map do |language_str|
      Language.find_by(name: language_str)
    end
  end

  def set_solutions
    @solutions = @user.solutions
  end

  def set_solution
    @solution = Solution.new
  end

  def solution_params
    params.require(:solution)
          .permit(:title, :instructions, :attempt, :programming_language, :tags, :language_id, :user_id)
  end
end

app/helpers/solutions_helper.rb
module SolutionsHelper
end

app/views/solutions/_edit_form.html.erb
<div class='w-full flex justify-center pt-8'>
  <div class='w-[48rem] px-4 pb-4'>
    <%= form_with(model: solution, 
                  url: update_solution_path(id: solution.id),
                  class: "flex flex-col gap-4 pb-4") do |form| %>
      <div class='flex flex-col gap-4 flex-grow'>
        <div
          class='
            mt-4 mx-4 pb-4 flex flex-col justify-center border-[1px] border-solid border-t-0
            border-l-0 border-r-0 border-gray-150
          '
        >
          <span class='text-2xl font-bold'>Submit a new solution</span>
          <p class='text-sm text-gray-400'>A solution is a successful attempt at solving a coding problem. So
            belated congratulations I guess!</p>
        </div>
        <div
          class='
            mx-4 flex flex-col gap-4 border-[1px] border-solid border-gray-150 border-t-0
            border-l-0 border-r-0 pb-4
          '
        >
          <p class='text-sm text-gray-400 italic'>All fields are necessary.</p>

          <div
            class='
              flex flex-col md:flex-row lg:flex-row justify-center items-start gap-4
            '
          >
            <div class='w-full md:min-w-[60%] lg:md:min-w-[60%] flex flex-col gap-1'>
              <%= form.label :title, class: "text-sm font-bold pb-1" %>
              <%= form.text_field :title,
                              class:
                                "w-full text-sm px-2 border-1[px] border-solid border-gray-150 bg-transparent placeholder:text-gray-150 rounded-md",
                              placeholder: "Does my number look big in this?" %>
            </div>
            <div class='w-full md:flex-grow lg:flex-grow flex flex-col gap-1'>
              <%= form.label :programming_language, class: "text-sm font-bold pb-1" %>
              <%= form.text_field :programming_language,
                              class:
                                "w-full text-sm px-2 border-1[px] border-solid border-gray-150 bg-transparent placeholder:text-gray-150 rounded-md",
                              placeholder: "Ruby" %>
            </div>
          </div>

          <p class='text-sm text-gray-400 italic'>
            Great solution titles are short and memorable. Need inspiration?
            How about
            <span class='font-bold text-green-400'>expert-octo-rotary-phone</span>
            ?
          </p>

          <div class='w-full flex flex-col gap-1'>
            <%= form.label :instructions, class: "text-sm font-bold pb-1" %>
            <%= form.text_area :instructions,
                           class:
                             "w-full text-sm px-2 border-1[px] border-solid border-gray-150 bg-transparent placeholder:text-gray-150 rounded-md",
                           placeholder:
                             "A Narcissistic Number (or Armstrong Number) is a positive number which is the sum of its own digits, each raised to the power of the number of digits in a given base. In this Kata, we will restrict ourselves to decimal (base 10).\n\nThe Challenge: Your code must return true or false (not 'true' and 'false') depending upon whether the given number is a Narcissistic number in base 10.",
                           rows: 6 %>
          </div>

          <div class='w-full flex flex-col gap-1'>
            <%= form.label :tags, class: "text-sm font-bold pb-1" %>
            <%= form.text_field :tags,
                            class:
                              "w-full text-sm px-2 border-1[px] border-solid border-gray-150 bg-transparent placeholder:text-gray-150 rounded-md",
                            placeholder: "mathematics, algorithms",
                            value:
                              solution.tags[0...-1].map { |tag|
                                "#{tag}, "
                              } << solution.tags.last %>
          </div>

          <p class='text-sm text-gray-400 italic'>
            Make<span class='text-green-400 font-bold'>,
            </span>sure<span class='text-green-400 font-bold'>,
            </span>each<span class='text-green-400 font-bold'>,
            </span>tag<span class='text-green-400 font-bold'>,
            </span>is<span class='text-green-400 font-bold'>,
            </span>separated<span class='text-green-400 font-bold'>,
            </span>by<span class='text-green-400 font-bold'>,
            </span>a<span class='text-green-400 font-bold'>,
            </span>comma.
          </p>

        </div>

        <div class='w-full px-4 pb-2 flex flex-col gap-1'>
          <%= form.label :attempt, class: "text-sm font-bold pb-1" %>
          <%= form.text_area :attempt,
                         class:
                           "w-full text-sm px-2 border-1[px] border-solid border-gray-150 bg-transparent placeholder:text-gray-150 rounded-md",
                         placeholder:
                           "def narcissistic?(num)\n\tnum == num.to_s.chars.map { |n| n.to_i**num.to_s.length }.sum\nend",
                         rows: 10 %>
        </div>
        <%= form.hidden_field :user_id,
                          class:
                            "text-sm mx-4 px-2 border-1[px] border-solid border-gray-150 bg-royal-500 placeholder:text-gray-150 rounded-md",
                          value: @user.id %>
        <div
          class='
            mx-4 py-4 border-[1px] border-solid border-gray-150 border-l-0 border-r-0
          '
        >
          <p class='text-sm text-gray-400 italic'><i class="fa-solid fa-hammer"></i>
            Before hitting
            <span class='text-green-400 font-bold'>Submit</span>, take your time to refactor.</p>
        </div>
        <div class='self-end'>
          <%= form.submit value: "Submit solution",
                      class:
                        "mx-4 px-4 py-2 text-sm rounded-md bg-green-700 cursor-pointer" %>

        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/solutions/_form.html.erb
<div class='w-full flex justify-center pt-8'>
  <div class='w-[48rem] px-4 pb-4'>
    <%= form_with(model: solution, 
                  url: create_new_solution_path,
                  class: "flex flex-col gap-4 pb-4") do |form| %>
      <div class='flex flex-col gap-4 flex-grow'>
        <div
          class='
            mt-4 mx-4 pb-4 flex flex-col justify-center border-[1px] border-solid border-t-0
            border-l-0 border-r-0 border-gray-150
          '
        >
          <span class='text-2xl font-bold'>Submit a new solution</span>
          <p class='text-sm text-gray-400'>A solution is a successful attempt at solving a coding problem. So
            belated congratulations I guess!</p>
        </div>
        <div
          class='
            mx-4 flex flex-col gap-4 border-[1px] border-solid border-gray-150 border-t-0
            border-l-0 border-r-0 pb-4
          '
        >
          <p class='text-sm text-gray-400 italic'>All fields are necessary, mate.</p>

          <div
            class='
              flex flex-col md:flex-row lg:flex-row justify-center items-start gap-4
            '
          >
            <div class='w-full md:min-w-[60%] lg:md:min-w-[60%] flex flex-col gap-1'>
              <%= form.label :title, class: "text-sm font-bold pb-1" %>
              <%= form.text_field :title,
                              class:
                                "w-full text-sm px-2 border-1[px] border-solid border-gray-150 bg-transparent placeholder:text-gray-150 rounded-md",
                              placeholder: "Does my number look big in this?" %>
            </div>
            <div class='w-full md:flex-grow lg:flex-grow flex flex-col gap-1'>
              <%= form.label :programming_language, class: "text-sm font-bold pb-1" %>
              <%= form.text_field :programming_language,
                              class:
                                "w-full text-sm px-2 border-1[px] border-solid border-gray-150 bg-transparent placeholder:text-gray-150 rounded-md",
                              placeholder: "Ruby",
                              value:
                                (
                                  if params[:programming_language]
                                    params[:programming_language]
                                  else
                                    ""
                                  end
                                ) %>
            </div>
          </div>

          <p class='text-sm text-gray-400 italic'>
            Great solution titles are short and memorable. Need inspiration?
            How about
            <span class='font-bold text-green-400'>expert-octo-rotary-phone</span>
            ?
          </p>

          <div class='w-full flex flex-col gap-1'>
            <%= form.label :instructions, class: "text-sm font-bold pb-1" %>
            <%= form.text_area :instructions,
                           class:
                             "w-full text-sm px-2 border-1[px] border-solid border-gray-150 bg-transparent placeholder:text-gray-150 rounded-md",
                           placeholder:
                             "A Narcissistic Number (or Armstrong Number) is a positive number which is the sum of its own digits, each raised to the power of the number of digits in a given base. In this Kata, we will restrict ourselves to decimal (base 10).\n\nThe Challenge: Your code must return true or false (not 'true' and 'false') depending upon whether the given number is a Narcissistic number in base 10.",
                           rows: 6 %>
          </div>

          <div class='w-full flex flex-col gap-1'>
            <%= form.label :tags, class: "text-sm font-bold pb-1" %>
            <%= form.text_field :tags,
                            class:
                              "w-full text-sm px-2 border-1[px] border-solid border-gray-150 bg-transparent placeholder:text-gray-150 rounded-md",
                            placeholder: "mathematics, algorithms" %>
          </div>

          <p class='text-sm text-gray-400 italic'>
            Make<span class='text-green-400 font-bold'>,
            </span>sure<span class='text-green-400 font-bold'>,
            </span>each<span class='text-green-400 font-bold'>,
            </span>tag<span class='text-green-400 font-bold'>,
            </span>is<span class='text-green-400 font-bold'>,
            </span>separated<span class='text-green-400 font-bold'>,
            </span>by<span class='text-green-400 font-bold'>,
            </span>a<span class='text-green-400 font-bold'>,
            </span>comma.
          </p>

        </div>

        <div class='w-full px-4 pb-2 flex flex-col gap-1'>
          <%= form.label :attempt, class: "text-sm font-bold pb-1" %>
          <%= form.text_area :attempt,
                         class:
                           "w-full text-sm px-2 border-1[px] border-solid border-gray-150 bg-transparent placeholder:text-gray-150 rounded-md",
                         placeholder:
                           "def narcissistic?(num)\n\tnum == num.to_s.chars.map { |n| n.to_i**num.to_s.length }.sum\nend",
                         rows: 10 %>
        </div>
        <%= form.hidden_field :user_id,
                          class:
                            "text-sm mx-4 px-2 border-1[px] border-solid border-gray-150 bg-royal-500 placeholder:text-gray-150 rounded-md",
                          value: @user.id %>
        <div
          class='
            mx-4 py-4 border-[1px] border-solid border-gray-150 border-l-0 border-r-0
          '
        >
          <p class='text-sm text-gray-400 italic'><i class="fa-solid fa-hammer"></i>
            Before hitting
            <span class='text-green-400 font-bold'>Submit</span>, take your time to refactor.</p>
        </div>
        <div class='self-end'>
          <%= form.submit value: "Submit solution",
                      class:
                        "mx-4 px-4 py-2 text-sm rounded-md bg-green-700 cursor-pointer" %>

        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/solutions/_solutions_in.html.erb
<div class='flex flex-col pb-4'>
  <div
    class='
      w-full flex flex-col md:flex-row lg:flex-row md:justify-between
      lg:justify-between md:items-center lg:items-center gap-4 text-md p-4
    '
  >
    <div>
      <span class='h-8'>
        <% if params[:programming_language] %>
          <a href="<%= overview_path(@user.alias) %>" class='text-blue-400'><%= @user.alias %></a>
          /
          <a href="<%= solutions_path(@user.alias) %>" class='text-blue-400'>Solutions</a>
          /
          <%= params[:programming_language] %>
        <% else %>
          <a href="<%= overview_path(@user.alias) %>" class='text-blue-400'><%= @user.alias %></a>
          / Solutions
        <% end %>
      </span>
    </div>
    <a
      href="<%= params[:programming_language] ? new_solution_path(programming_language: params[:programming_language]) : new_solution_path %>"
    >
      <button
        class='
          text-xs md:text-sm lg:text-sm rounded-md bg-green-700 px-4 py-2 w-full
        '
      >
        <%= "New solution #{params[:programming_language] ? "in " + params[:programming_language] : ""}" %>
      </button>
    </a>
  </div>
  <div
    class='
      flex flex-col md:flex-col-reverse lg:flex-row justify-between items-start gap-0
    '
  >
    <div class='flex flex-col gap-4 px-4 w-full md:flex-grow lg:flex-grow'>
      <% solutions_to_show =
        (
          if params[:programming_language]
            @user
              .solutions_in(params[:programming_language])
              .sort { |a, b| b.updated_at <=> a.updated_at }
          else
            @solutions.sort { |a, b| b.updated_at <=> a.updated_at }
          end
        ) %>
      <% if !solutions_to_show.empty? %>
        <% solutions_to_show.each do |solution| %>
          <div
            class='
              flex flex-col gap-4 pb-4 rounded-md border-[1px] border-solid border-gray-150
            '
          >
            <div class='flex flex-col gap-4 flex-grow'>
              <div class='rounded-t-md p-4 bg-gray-600 flex justify-between items-center'>
                <span class='text-sm font-bold'><%= solution.title %></span>
                <span class='text-sm font-bold'><%= solution.updated_at.strftime("%B %d") %></span>
              </div>
              <span class='px-4 text-sm text-gray-400'>INSTRUCTIONS:</span>
              <p class='px-4 text-sm text-gray-400 whitespace-pre-wrap'><%= solution.instructions %></p>
              <code
                class='
                  text-xs px-4 py-6 border-[1px] border-solid border-gray-150 border-l-0
                  border-r-0 bg-royal-500 whitespace-pre-wrap
                '
              ><%= solution.attempt %></code>
              <div class='px-4 flex items-center '>
                <span class='text-xs'>
                  Tags:&nbsp;&nbsp;
                </span>
                <ul class='flex flex-wrap gap-2'>
                  <% solution.tags.each do |tag| %>
                    <li
                      class='
                        text-xs border-[1px] border-solid border-gray-150 px-2 py-1 rounded-md
                      '
                    ><%= tag %></li>
                  <% end %>
                </ul>
              </div>
              <div class='text-xs px-4 pt-4 flex gap-1'>
                <%= solution.programming_language %>
                <span class='text-gray-100'>&nbsp;·&nbsp;</span>
                <%= link_to "Refactor",
                edit_solution_path(solution, alias: @user.alias),
                class: "text-blue-400" %>
                <span class='text-gray-100'>&nbsp;·&nbsp;</span>
                <%= button_to "Delete", solution, method: :delete, class: "text-red-400" %>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <div
          class='
            px-4 py-2 w-full flex items-center border-[1px] border-solid border-gray-150
            rounded-md
          '
        >
          <div class='flex flex-col text-sm'>
            <span>Oops! No solutions yet...</span>
          </div>
        </div>

      <% end %>
    </div>
    <div
      class='
        min-w-64 w-full md:w-full lg:max-w-72 flex flex-col gap-4 mr-4 text-sm pt-4 pb-4
        px-4 md:pt-0 lg:pl-0 lg:px-0 lg:pt-0
      '
    >
      <div
        class='
          flex flex-col gap-4 border-[1px] border-solid border-gray-150 border-t-0
          border-l-0 border-r-0 pb-4
        '
      >
        <span class='text-gray-400 font-bold'>
          <%= params[:programming_language] ? "Language" : "Languages" %>
        </span>
        <%= params[:programming_language] ? params[:programming_language] : @languages.count %>
      </div>
      <div
        class='
          flex flex-col gap-4 border-[1px] border-solid border-gray-150 border-t-0
          border-l-0 border-r-0 py-4
        '
      >
        <span class='text-gray-400 font-bold'>Solutions</span>
        <% if params[:programming_language] %>
          <%= @user.solutions_in(params[:programming_language]).count %>
        <% else %>
          <%= @user.solutions.count %>
        <% end %>
      </div>
      <div
        class='
          flex flex-col gap-4 border-[1px] border-solid border-gray-150 border-t-0
          border-l-0 border-r-0 py-4
        '
      >
        <span class='text-gray-400 font-bold'>Tags</span>
        <ul class='flex flex-wrap gap-2'>
          <% if params[:programming_language] %>
            <% @user
              .solutions_in(params[:programming_language])
              .map(&:tags)
              .flatten
              .each_with_object(Hash.new(0)) { |curr, acc| acc[curr.strip] += 1 } 
              .sort_by { |key, value| -value }
              .each do |key, val| %>
              <li
                class='
                  text-xs border-[1px] border-solid border-gray-150 px-2 py-1 rounded-md flex
                  justify-between gap-2 items-center
                '
              >
                <span><%= key %></span>
                <span class='rounded-2xl border-[1px] border-solid border-gray-150 px-2'><%= val %></span>
              </li>
            <% end %>
          <% else %>
            <% @user
              .solutions
              .map(&:tags)
              .flatten
              .each_with_object(Hash.new(0)) { |curr, acc| acc[curr.strip] += 1 } 
              .sort_by { |key, value| -value }
              .each do |key, val| %>
              <li
                class='
                  text-xs border-[1px] border-solid border-gray-150 px-2 py-1 rounded-md flex
                  justify-between gap-2 items-center
                '
              >
                <span><%= key %></span>
                <span class='rounded-2xl border-[1px] border-solid border-gray-150 px-2'><%= val %></span>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/solutions/edit.html.erb
<%= render "edit_form", solution: @user.solutions.find(params[:id]) %>

app/views/solutions/index.html.erb
<div
  class='
    flex flex-col md:flex-row lg:flex-row justify-between gap-0 border-[1px]
    border-solid border-gray-150 border-t-0 border-l-0 border-r-0 min-h-screen
  '
>
  <div
    class='
      min-w-64 sm:w-full md:max-w-64 lg:max-w-72 border-[1px] border-solid
      border-gray-150 border-t-0 border-l-0 border-b-0 overflow-y-auto
    '
  >
    <div class='h-full flex flex-col text-md'>
      <div
        class='
          text-md border-[1px] border-solid border-gray-150 border-t-0 border-l-0
          border-r-0 p-4 flex flex-col justify-between gap-4
        '
      >
        <h2>Languages</h2>
      </div>
      <div class='h-full p-4 text-sm overflow-auto'>
        <%#= render "languages/form" %>
        <div class='justify-center pl-0'>
          <a href="<%= solutions_path(@user.alias) %>">
            <button
              class='
                flex items-center gap-2 w-full p-2 hover:bg-gray-150 rounded-md
              '
            >
              <i class="fa-solid fa-glasses text-gray-400"></i>
              <%= @user.alias %>
              <span
                class='
                  border-[1px] border-solid border-gray-150 rounded-2xl px-2 text-xs
                  <%= current_page?(solutions_path(@user.alias)) ? 'bg-blue-400 text-royal-500' : 'bg-transparent text-gray-200' %>
                '
              >
                <%= @solutions.count %>
              </span>
            </button>
          </a>
        </div>
        <% @languages.each do |language| %>
          <%# weird behavior where if this condition is not set up, a params error shows up %>
          <% if language.name %>
            <a
              href="<%= solutions_in_language_path(programming_language: language.name) %>"
              class='flex items-center gap-2 pl-2'
            >
              <button class='w-full flex items-center gap-2 p-2 hover:bg-gray-150 rounded-md'>
                └─
                <i class="fa-solid fa-keyboard text-gray-400"></i>
                <span><%= language.name %></span>
                <span
                  class='
                    border-[1px] border-solid border-gray-150 rounded-2xl px-2 text-xs
                    <%= request.path.include?(language.name) ? 'bg-blue-400 text-royal-500' : 'bg-transparent text-gray-200' %>
                  '
                >
                  <%= @user
                    .solutions
                    .filter { |solution| solution.programming_language == language.name }
                    .count %>
                </span>
              </button>
            </a>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class='flex-grow'>
    <%= render "solutions_in" %>
  </div>
</div>

app/views/solutions/new.html.erb
<%= render "form", solution: @solution %>