config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :languages
    resources :solutions
  end

  get '/signup', to: 'users#new', as: 'signup'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  root 'sessions#new'
  post '/sessions', to: 'sessions#create'
  post 'users', to: 'users#create', as: 'create_user'

  get ':alias/overview', to: 'headquarters#overview', as: 'overview'

  get '/:alias/solutions', to: 'solutions#index', as: 'solutions'
  get '/:alias/solutions/:programming_language', to: 'solutions#index', as: 'solutions_in_language'
  get '/:alias/new_solution/', to: 'solutions#new', as: 'new_solution'
  post '/:alias/solutions', to: 'solutions#create', as: 'create_new_solution'
  get '/:alias/solutions/edit/:id', to: 'solutions#edit', as: 'edit_solution'
  patch '/:alias/solutions/:id', to: 'solutions#update', as: 'update_solution'
  get 'solution/:id', to: 'solutions#show', as: 'solution'
  delete 'solution/:id', to: 'solutions#destroy', as: 'destroy_solution'

  get 'languages/new', to: 'langauges#new', as: 'new_languages'
  # get 'solutions/new/:programming_language', to: 'solutions#new', as: 'new_solution_in_language'
  post 'languages', to: 'languages#create'
end

app/views/layouts/_app_defaults.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= javascript_importmap_tags %>

app/views/layouts/_header.html.erb
<header class='bg-royal-500'>
  <div class='px-4 h-14 pt-4 pb-2 flex justify-between items-center'>
    <div class='flex items-center gap-3'>
      <div
        class='
          h-8 w-8 border-2 border-gray-100 rounded-full flex justify-center items-center
        '
      >
        <a href=<%= overview_path(@user.alias) %>>
          <i class="fa-solid fa-vial fa-md text-gray-100"></i>
        </a>
      </div>
      <div
        class='
          flex flex-col md:flex-row lg:flex-row md:items-center lg:items-center text-xs
        '
      >
        <span class='text-gray-200 md:text-sm lg:text-sm'>Solvent&nbsp;/&nbsp;</span>
        <strong class="text-gray-100 text-sm">
          <span><%= @user.alias if @user %></span>
        </strong>
      </div>
    </div>
    <div class='flex items-center gap-4'>
      <%= button_to logout_path, method: :delete, class: 'h-8 w-8 border-[1px] border-solid border-gray-400 rounded-md flex justify-center items-center text-gray-400' do %>
        <i class="fa-solid fa-right-from-bracket"></i>
      <% end %>
      <%= identicon_for user: @user if @user %>
    </div>
  </div>
  <nav
    class='
      px-4 h-12 flex justify-between items-center border-[1px] border-solid
      border-gray-150 border-t-0 border-l-0 border-r-0
    '
  >
    <ul
      class='
        flex items-center gap-4 text-xs md:text-sm lg:text-sm text-gray-100
      '
    >
      <li
        class='
          h-12 border-2 border-solid <%= request.path.include?('overview') ? 'border-red-400 font-bold' : 'border-transparent font-medium' %> border-t-0
          border-l-0 border-r-0 flex items-center
        '
      >
        <a href="<%= overview_path(@user.alias) %>" class='flex items-center gap-2'>
          <i class="fa-solid fa-book-open"></i>
          <span>Overview</span>
        </a>
      </li>
      <li
        class='
          h-12 border-2 border-solid <%= request.path.include?('solution') ? 'border-red-400 font-bold' : 'border-transparent font-medium' %> border-t-0
          border-l-0 border-r-0 flex items-center
        '
      >
        <a href="<%= solutions_path(@user.alias) %>" class='flex items-center gap-2'>
          <i class="fa-solid fa-flask-vial"></i>
          <span>Solutions</span>
        </a>
      </li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gisthub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link
      href="https://fonts.googleapis.com/css?family=Inter&display=swap"
      rel="stylesheet"
    >

    <%= render "layouts/app_defaults" %>
  </head>
  <body class='bg-gray-500 text-gray-100'>
    <%= render "layouts/header" if @current_user %>
    <main class='overflow-auto'>
      <%= yield %>
    </main>

  </body>
</html>